// Carga inicial de productos a partir de la lista de precios y flyers de RODASUR.
// Ejecuta con: npm run seed   (borra y recarga el catálogo de ejemplo)
const db = require('./database');

const CAMPAIGN_VALID_UNTIL = '2026-07-30'; // "Válido hasta el 30 de Julio o agotar stock"

const products = [
  // ---------------- EXTRACTORES HIDRÁULICOS ----------------
  {
    code: 'HSP-63',
    name: 'Extractor Hidráulico HSP-63 (6 Toneladas)',
    brand: 'BETEX',
    category: 'Extractores',
    description: 'Extractor hidráulico de 6 toneladas con autocentrado, ideal para aplicaciones exigentes en espacios reducidos y componentes ajustados. Máxima versatilidad en cada uso.',
    features: [
      'Extractor de 6 toneladas con auto centrado',
      'Diseño compacto y eficiente',
      'Ideal para rodamientos, engranajes, poleas y bujes',
      'Máxima versatilidad, sin equivalente directo',
    ],
    specs: [
      { param: 'Capacidad de extracción', value: '6 toneladas', description: 'Capacidad máxima' },
      { param: 'Fuerza de tracción', value: '55 kN', description: 'Fuerza de tracción' },
      { param: 'Apertura máxima (Wmax)', value: '390 mm', description: 'Apertura máxima' },
      { param: 'Profundidad máxima (Lmax)', value: '230 mm', description: 'Profundidad máxima' },
      { param: 'Carrera', value: '70 mm', description: 'Carrera del émbolo' },
      { param: 'Peso', value: '10 kg', description: 'Peso aproximado' },
    ],
    price_regular: 1083.28,
    price_discount: 996.62,
    image: '/uploads/9_9.png',
  },
  {
    code: 'HSP-83',
    name: 'Extractor Hidráulico HSP-83 (8 Toneladas)',
    brand: 'BETEX',
    category: 'Extractores',
    description: 'Extractor hidráulico robusto y de alto rendimiento con bomba hidráulica integrada. Amplio rango de trabajo hasta 460 mm de apertura, diseñado para trabajos exigentes y alineación precisa.',
    features: [
      'Bomba hidráulica integrada de alto rendimiento',
      'Amplio rango de trabajo: hasta 460 mm de apertura y 280 mm de profundidad',
      'Diseño optimizado para máxima alineación',
      'Robusto y de alto rendimiento',
    ],
    specs: [
      { param: 'Capacidad de extracción', value: '8 toneladas', description: 'Capacidad máxima' },
      { param: 'Fuerza de tracción', value: '75 kN', description: 'Fuerza de tracción' },
      { param: 'Apertura máxima (Wmax)', value: '460 mm', description: 'Apertura máxima' },
      { param: 'Profundidad máxima (Lmax)', value: '280 mm', description: 'Profundidad máxima' },
      { param: 'Carrera', value: '85 mm', description: 'Carrera del émbolo' },
      { param: 'Peso', value: '12 kg', description: 'Peso aproximado' },
    ],
    price_regular: 786.64,
    price_discount: 723.71,
    image: '/uploads/9_9.png',
  },

  // ---------------- EXTRACTORES MECÁNICOS ----------------
  {
    code: 'MSP-2/3-180',
    name: 'Extractor Mecánico MSP-2/3-180 (2 o 3 brazos)',
    brand: 'BETEX',
    category: 'Extractores',
    description: 'Extractor mecánico convertible de 2 o 3 brazos con sistema autocentrado. Mayor agilidad y ajuste automático, ideal para rodamientos y poleas medianas y pequeñas.',
    features: [
      'Convertible de 2 o 3 brazos',
      'Sistema autocentrado con ajuste automático',
      'Brazos reversibles',
      'Ideal para rodamientos y poleas medianas y pequeñas',
    ],
    specs: [
      { param: 'Tipo de extractor', value: '2 o 3 brazos (convertible)', description: 'Configuración' },
      { param: 'Sistema', value: 'Autocentrado', description: 'Sistema de sujeción' },
      { param: 'Apertura máxima (Wmax)', value: '180 mm', description: 'Apertura máxima' },
      { param: 'Profundidad de agarre (Tmax)', value: '120 mm', description: 'Profundidad de agarre' },
      { param: 'Anchura de agarre máx. (d)', value: '6 mm', description: 'Anchura de agarre máxima' },
      { param: 'Fuerza de tracción (F1)', value: '25 kN', description: 'Fuerza de tracción' },
      { param: 'Peso', value: '2.3 kg', description: 'Peso aproximado' },
    ],
    price_regular: 241.18,
    price_discount: 221.88,
    image: '/uploads/7_7.png',
  },
  {
    code: 'MSP-2/3-300',
    name: 'Extractor Mecánico MSP-2/3-300 (2 o 3 brazos)',
    brand: 'BETEX',
    category: 'Extractores',
    description: 'Extractor mecánico convertible de 2 o 3 brazos con sistema autocentrado. Mayor capacidad de apertura y profundidad, ideal para componentes de gran diámetro.',
    features: [
      'Convertible de 2 o 3 brazos',
      'Sistema autocentrado que optimiza los tiempos de preparación',
      'Brazos reversibles',
      'Ideal para componentes de gran diámetro',
    ],
    specs: [
      { param: 'Tipo de extractor', value: '2 o 3 brazos (convertible)', description: 'Configuración' },
      { param: 'Sistema', value: 'Autocentrado', description: 'Sistema de sujeción' },
      { param: 'Apertura máxima (Wmax)', value: '300 mm', description: 'Apertura máxima' },
      { param: 'Profundidad de agarre (Tmax)', value: '210 mm', description: 'Profundidad de agarre' },
      { param: 'Anchura de agarre máx. (d)', value: '13 mm', description: 'Anchura de agarre máxima' },
      { param: 'Fuerza de tracción (F1)', value: '75 kN', description: 'Fuerza de tracción' },
      { param: 'Peso', value: '6.1 kg', description: 'Peso aproximado' },
    ],
    price_regular: 336.34,
    price_discount: 309.43,
    image: '/uploads/7_7.png',
  },

  // ---------------- HERRAMIENTAS DE MONTAJE (BEARING-MATE) ----------------
  {
    code: 'BEARING-MATE250-450',
    name: 'Bearing-Mate 250-450',
    brand: 'SCHAEFFLER',
    category: 'Herramientas de Montaje',
    description: 'Solución práctica y segura para el transporte y montaje de rodamientos autoalineantes de tamaño medio, evitando daños y facilitando su instalación.',
    features: [
      'Diseño robusto de alta calidad para uso profesional',
      'Transporte seguro de rodamientos',
      'Montaje fácil y rápido',
      'Para rodamientos autoalineantes de tamaño medio',
    ],
    specs: [
      { param: 'Rango de trabajo', value: '250 - 450 mm', description: 'Diámetro de rodamiento' },
      { param: 'Aplicación', value: 'Rodamientos autoalineantes de tamaño medio', description: 'Uso ideal' },
      { param: 'Material', value: 'Acero inoxidable y polímero reforzado', description: 'Material de fabricación' },
    ],
    price_regular: 1340.01,
    price_discount: 1232.81,
    image: '/uploads/1_1.png',
  },
  {
    code: 'BEARING-MATE450-650',
    name: 'Bearing-Mate 450-650',
    brand: 'SCHAEFFLER',
    category: 'Herramientas de Montaje',
    description: 'Herramienta de transporte y montaje para rodamientos de mayor envergadura. Diseño robusto que permite un montaje seguro y eficiente.',
    features: [
      'Diseño robusto de alta calidad',
      'Transporte seguro de rodamientos de mayor envergadura',
      'Montaje fácil y rápido',
      'Para rodamientos de mayor envergadura',
    ],
    specs: [
      { param: 'Rango de trabajo', value: '450 - 650 mm', description: 'Diámetro de rodamiento' },
      { param: 'Aplicación', value: 'Rodamientos de mayor envergadura', description: 'Uso ideal' },
      { param: 'Material', value: 'Acero inoxidable y polímero reforzado', description: 'Material de fabricación' },
    ],
    price_regular: 1371.15,
    price_discount: 1261.46,
    image: '/uploads/1_1.png',
  },
  {
    code: 'BEARING-MATE650-850',
    name: 'Bearing-Mate 650-850',
    brand: 'SCHAEFFLER',
    category: 'Herramientas de Montaje',
    description: 'Herramienta de transporte y montaje para rodamientos de gran tamaño. Materiales de alta calidad para un uso profesional y duradero.',
    features: [
      'Diseño robusto de alta calidad',
      'Transporte seguro de rodamientos de gran tamaño',
      'Montaje fácil y rápido',
      'Para rodamientos de gran tamaño',
    ],
    specs: [
      { param: 'Rango de trabajo', value: '650 - 850 mm', description: 'Diámetro de rodamiento' },
      { param: 'Aplicación', value: 'Rodamientos de gran tamaño', description: 'Uso ideal' },
      { param: 'Material', value: 'Acero inoxidable y polímero reforzado', description: 'Material de fabricación' },
    ],
    price_regular: 1375.36,
    price_discount: 1265.33,
    image: '/uploads/1_1.png',
  },

  // ---------------- CALENTADORES POR INDUCCIÓN ----------------
  {
    code: 'HEATER100-SMART-240V-US',
    name: 'Calentador por Inducción HEATER100-SMART (100 kg / 240 °C)',
    brand: 'SCHAEFFLER',
    category: 'Calentadores por Inducción',
    description: 'Dispositivo de calentamiento inductivo con capacidad de hasta 100 kg y pantalla táctil. Interfaz táctil inteligente con monitoreo térmico avanzado para control total del ciclo de calentamiento.',
    features: [
      'Pantalla táctil con monitoreo térmico avanzado',
      'Precisión inteligente para control total del ciclo',
      'Eficiencia y rendimiento: calentamiento rápido y uniforme',
      'Robustez industrial, capacidad de hasta 100 kg',
    ],
    specs: [
      { param: 'Tensión (U)', value: '230 V', description: 'Tensión de funcionamiento' },
      { param: 'Frecuencia (f)', value: '50 - 60 Hz', description: 'Frecuencia' },
      { param: 'Consumo (P)', value: '3,7 kVA', description: 'Consumo de energía' },
      { param: 'Corriente (I)', value: '16 A', description: 'Valor actual' },
      { param: 'Temperatura máx. (θmax)', value: '240 °C', description: 'Temperatura máx. de calentamiento' },
      { param: 'Tiempo de calentamiento', value: '0 - 99 min', description: 'Rango de tiempo' },
      { param: 'Pantalla', value: 'Touch', description: 'Pantalla táctil' },
      { param: 'Sondas magnéticas', value: '2 (estándar)', description: 'Cantidad de sondas' },
      { param: 'Peso', value: '34,6 kg', description: 'Peso' },
    ],
    price_regular: 3931.25,
    price_discount: 3616.75,
    image: '/uploads/2_2.png',
  },
  {
    code: 'HEATER20-BASIC-240V-US',
    name: 'Calentador Inductivo HEATER20-BASIC (20 kg / 150 °C)',
    brand: 'SCHAEFFLER',
    category: 'Calentadores por Inducción',
    description: 'Solución compacta y accesible para calentamiento preciso de rodamientos pequeños y aplicaciones de baja intensidad. Incluye maletín resistente y sonda magnética.',
    features: [
      'Seguridad integrada contra sobrecalentamientos',
      'Rápido y eficiente: calentamiento ajustable de 6 a 30 minutos',
      'Sonda magnética incluida',
      'Compacto y portátil con maletín resistente',
    ],
    specs: [
      { param: 'Tensión (U)', value: '230 V', description: 'Tensión de funcionamiento' },
      { param: 'Frecuencia (f)', value: '50 - 60 Hz', description: 'Frecuencia' },
      { param: 'Consumo (P)', value: '1,2 kVA', description: 'Consumo de energía' },
      { param: 'Corriente (I)', value: '5 A', description: 'Valor actual' },
      { param: 'Temperatura máx. (θmax)', value: '150 °C', description: 'Temperatura máx. de calentamiento' },
      { param: 'Tiempo de calentamiento', value: '0 - 30 min', description: 'Rango de tiempo' },
      { param: 'Pantalla', value: 'Digital', description: 'Tipo de pantalla' },
      { param: 'Sonda magnética', value: '1', description: 'Cantidad de sondas' },
      { param: 'Peso', value: '10,3 kg', description: 'Peso' },
    ],
    price_regular: 2223.07,
    price_discount: 2045.23,
    image: '/uploads/3_3.png',
  },
  {
    code: 'MF-GENERATOR3.0-3.5KW-230',
    name: 'Generador de Inducción MF 3.0 - 3.5 kW (230 V)',
    brand: 'SCHAEFFLER',
    category: 'Calentadores por Inducción',
    description: 'Inducción de media frecuencia con inductores flexibles para garantizar tasas irregulares y zonas de difícil acceso. Alto rendimiento para aplicaciones industriales exigentes.',
    features: [
      'Potente y eficiente: 3.0 - 3.5 kW de potencia',
      'Inducción de media frecuencia para mayor alcance',
      'Calentamiento controlado hasta 180 °C',
      'Compacto y portátil, fácil conexión a 230 V monofásico',
    ],
    specs: [
      { param: 'Potencia (P)', value: '3,5 kW', description: 'Potencia' },
      { param: 'Rango de frecuencia MF', value: '10 - 50 kHz', description: 'Frecuencia media' },
      { param: 'Tensión (U)', value: '230 V', description: 'Tensión' },
      { param: 'Alimentación', value: 'CA', description: 'Tipo de corriente' },
      { param: 'Corriente (I)', value: '16 A', description: 'Amperaje' },
      { param: 'Frecuencia de potencia (f)', value: '50 - 60 Hz', description: 'Frecuencia' },
      { param: 'Visualización', value: '4,3"', description: 'Visualización de cotas' },
      { param: 'Dimensiones', value: '320 x 350 x 150 mm', description: 'L x An x Al' },
      { param: 'Peso', value: '7,85 kg', description: 'Peso' },
    ],
    price_regular: 5813.64,
    price_discount: 5348.55,
    image: '/uploads/8_8.png',
  },
  {
    code: 'MF-IDUCTOR-2.3KW-230V',
    name: 'Calentador por Inducción Portátil MF 2.3 kW (230 V)',
    brand: 'SCHAEFFLER',
    category: 'Calentadores por Inducción',
    description: 'Calentador manual de inducción MF con inductor flexible (2 m) y guantes de protección contra el calor. Permite calentar todo tipo de piezas metálicas: rodamientos, poleas y más.',
    features: [
      'Equipo portátil y fácil de usar',
      'Incluye inductor flexible de 2 m y guantes de protección',
      'Calentamiento rápido y seguro',
      'Ideal para rodamientos, poleas y piezas metálicas',
    ],
    specs: [
      { param: 'Potencia (P)', value: '2.3 kW', description: 'Potencia' },
      { param: 'Rango de frecuencia MF', value: '30 - 65 kHz', description: 'Frecuencia media' },
      { param: 'Tensión (U)', value: '230 V', description: 'Tensión' },
      { param: 'Alimentación', value: 'CA', description: 'Tipo de corriente' },
      { param: 'Corriente (I)', value: '10 A', description: 'Amperaje' },
      { param: 'Frecuencia de potencia (f)', value: '50 - 60 Hz', description: 'Frecuencia' },
      { param: 'Visualización', value: '4.3"', description: 'Visualización de cotas' },
      { param: 'Dimensiones', value: '401 x 132 x 71 mm', description: 'L x An x Al del generador' },
      { param: 'Peso', value: '1.4 kg', description: 'Peso' },
    ],
    price_regular: 1607.75,
    price_discount: 1479.13,
    image: '/uploads/5_5.png',
  },

  // ---------------- ACCESORIOS DE INDUCCIÓN ----------------
  {
    code: 'MF-INDUCTOR-2.3KW-D3.5-SE',
    name: 'Inductor Flexible MF 2.3 kW D3.5-SE',
    brand: 'SCHAEFFLER',
    category: 'Accesorios de Inducción',
    description: 'Accesorio inductor flexible para calentadores de inducción MF de hasta 2.3 kW. Diámetro interior de devanado de 18 a 52 mm.',
    features: [
      'Accesorio para calentadores de inducción MF',
      'Diámetro interior de devanado 18 - 52 mm',
      'Temperatura máx. permitida 325 °C',
      'Se vende por separado',
    ],
    specs: [
      { param: 'Diámetro del cable (L)', value: '3.5 mm', description: 'Diámetro del cable' },
      { param: 'Diámetro interior del devanado (D)', value: '18 - 52 mm', description: 'Diámetro interior del devanado' },
      { param: 'Potencia máx. (Pmax)', value: '2.3 kW', description: 'Para generadores con potencia máx.' },
      { param: 'Temperatura máx. (Tmax)', value: '325 °C', description: 'Temperatura máx. de calentamiento permitida' },
      { param: 'Diámetro mín. de devanado (d)', value: '75 mm', description: 'Diámetro mín. de devanado (aprox.)' },
      { param: 'Peso', value: '0,029 kg', description: 'Peso' },
    ],
    price_regular: 449.87,
    price_discount: 413.88,
    image: '/uploads/5_5.png',
  },
  {
    code: 'MF-INDUCTOR-3.5KW-7.5M-D1',
    name: 'Inductor Flexible MF 3.5 kW 7.5 m D1',
    brand: 'SCHAEFFLER',
    category: 'Accesorios de Inducción',
    description: 'Inductor flexible de 7.5 m para generadores de inducción MF de 3.5 kW. Ideal para zonas de difícil acceso.',
    features: [
      'Inductor flexible de 7,5 m de longitud',
      'Para generadores con potencia máx. de 3.5 kW',
      'Temperatura máx. permitida 180 °C',
      'Se vende por separado',
    ],
    specs: [
      { param: 'Longitud (L)', value: '7,5 m', description: 'Longitud' },
      { param: 'Diámetro del cable (D)', value: '12 mm', description: 'Diámetro del cable' },
      { param: 'Potencia máx. (Pmax)', value: '3,5 kW', description: 'Para generadores con potencia máx.' },
      { param: 'Temperatura máx. (θmax)', value: '180 °C', description: 'Temperatura máx. de calentamiento permitida' },
      { param: 'Diámetro mín. de devanado (d)', value: '75 mm', description: 'Diámetro mín. de devanado (aprox.)' },
      { param: 'Peso', value: '1,95 kg', description: 'Peso' },
    ],
    price_regular: 464.33,
    price_discount: 427.18,
    image: '/uploads/8_8.png',
  },
  {
    code: 'MF-INDUCTOR.MAGNET-D12',
    name: 'Soporte Magnético para Inductor MF D12',
    brand: 'SCHAEFFLER',
    category: 'Accesorios de Inducción',
    description: 'Set de soportes magnéticos (5 piezas) para inductores flexibles de generadores de 3.5 kW. Fijación segura y estable del inductor.',
    features: [
      'Set de 5 piezas magnet holder',
      'Para inductores flexibles de generador 3,5 kW',
      'Fijación segura y estable',
      'Se vende por separado',
    ],
    specs: [
      { param: 'Usabilidad', value: 'Para inductores flexibles de generador 3,5 kW', description: 'Compatibilidad' },
      { param: 'Volumen de suministro', value: '5 piezas magnet holder', description: 'Contenido' },
      { param: 'Peso', value: '33 g', description: 'Peso' },
    ],
    price_regular: 101.31,
    price_discount: 93.21,
    image: '/uploads/8_8.png',
  },

  // ---------------- INSTRUMENTOS DE MEDICIÓN ----------------
  {
    code: 'LASER-SMARTY3',
    name: 'Sistema Láser de Alineación de Poleas SMARTY3',
    brand: 'SCHAEFFLER',
    category: 'Instrumentos de Medición',
    description: 'Sistema láser para alineación de poleas en transmisión por correas. Haz láser para verificar alineación paralela y angular mediante blancos magnéticos de alta precisión.',
    features: [
      'Máxima precisión con tecnología láser',
      'Ahorra tiempo de mantenimiento',
      'Portátil e intuitivo',
      'Incluye blancos magnéticos para fijación segura',
    ],
    specs: [
      { param: 'Diámetro de la polea', value: '≥ 60 mm', description: 'Diámetro mínimo de polea' },
      { param: 'Distancia de medición mín.', value: '40 mm', description: 'Distancia mínima' },
      { param: 'Distancia de medición máx.', value: '10 m', description: 'Distancia máxima' },
      { param: 'Clase de seguridad láser', value: 'Clase 2 acc. to IEC 60825-1', description: 'Láser de clase de seguridad' },
      { param: 'Potencia de salida', value: '< 4.8 mW', description: 'Potencia de salida' },
      { param: 'Longitud de onda', value: '635 - 670 nm', description: 'Láser de longitud de onda' },
      { param: 'Ángulo del haz', value: '60°', description: 'Ángulo del haz' },
      { param: 'Tipo de batería', value: '1x R6 (AA) 1.5 V', description: 'Tipo de batería' },
      { param: 'Autonomía', value: 'hasta 12 h continuas', description: 'Funcionamiento con batería' },
      { param: 'Material', value: 'ABS plastic / hard anodized aluminium', description: 'Material' },
      { param: 'Dimensiones', value: '145 x 86 x 30 mm', description: 'Cotas (L x An x Al)' },
      { param: 'Peso', value: '0.265 kg', description: 'Peso' },
    ],
    price_regular: 1451.03,
    price_discount: 1334.94,
    image: '/uploads/4_4.png',
  },
  {
    code: 'LASER-TRUMMY2',
    name: 'Medidor Electrónico de Tensión de Correas TRUMMY2',
    brand: 'SCHAEFFLER',
    category: 'Instrumentos de Medición',
    description: 'Medidor electrónico de tensión de correas con tecnología láser para una medición precisa y confiable en transmisiones por correas. Diseño compacto e intuitivo.',
    features: [
      'Medición precisa con tecnología láser',
      'Rápido y eficiente: mediciones en segundos',
      'Portátil y fácil de usar',
      'Verificación sin contacto directo con la correa',
    ],
    specs: [
      { param: 'Frecuencia del rango de medición', value: '10 Hz - 800 Hz', description: 'Rango de frecuencia' },
      { param: 'Banda libre mínima de filamento', value: '> 150 mm', description: 'Banda libre mínima' },
      { param: 'Error de muestreo digital', value: '< 1%', description: 'Error de muestreo' },
      { param: 'Error de visualización', value: '≤ 1 Hz', description: 'Error de visualización' },
      { param: 'Error total', value: '< 5%', description: 'Error total' },
      { param: 'Temperatura de funcionamiento', value: '+10 °C ... +50 °C', description: 'Temperatura de funcionamiento' },
      { param: 'Material del alojamiento', value: 'Plastic (ABS)', description: 'Material' },
      { param: 'Pantalla', value: '2 líneas LCD, 16 caracteres', description: 'Pantalla' },
      { param: 'Idiomas disponibles', value: '10', description: 'Idiomas' },
      { param: 'Fuente de alimentación', value: 'Battery (9 V)', description: 'Batería' },
      { param: 'Dimensiones del dispositivo', value: '80 x 126 x 37 mm', description: 'Cotas (mm)' },
      { param: 'Dimensiones del estuche', value: '255 x 210 x 60 mm', description: 'Cotas del estuche (mm)' },
      { param: 'Peso', value: '0.08 kg', description: 'Peso' },
    ],
    price_regular: 644.63,
    price_discount: 593.06,
    image: '/uploads/6_6.png',
  },
];

function seed() {
  const insert = db.prepare(`
    INSERT INTO products
      (code, name, brand, category, description, features, specs,
       price_regular, price_discount, image, stock, on_discount, active, valid_until)
    VALUES
      (@code, @name, @brand, @category, @description, @features, @specs,
       @price_regular, @price_discount, @image, @stock, 1, 1, @valid_until)
    ON CONFLICT(code) DO UPDATE SET
      name           = excluded.name,
      brand          = excluded.brand,
      category       = excluded.category,
      description    = excluded.description,
      features       = excluded.features,
      specs          = excluded.specs,
      price_regular  = excluded.price_regular,
      price_discount = excluded.price_discount,
      image          = excluded.image,
      valid_until    = excluded.valid_until,
      updated_at     = datetime('now')
  `);

  const tx = db.transaction((rows) => {
    for (const p of rows) {
      insert.run({
        code: p.code,
        name: p.name,
        brand: p.brand,
        category: p.category,
        description: p.description,
        features: JSON.stringify(p.features || []),
        specs: JSON.stringify(p.specs || []),
        price_regular: p.price_regular,
        price_discount: p.price_discount,
        image: p.image || null,
        stock: p.stock != null ? p.stock : 10,
        valid_until: CAMPAIGN_VALID_UNTIL,
      });
    }
  });

  tx(products);
  const total = db.prepare('SELECT COUNT(*) AS n FROM products').get().n;
  console.log(`[seed] Catálogo cargado. Total de productos en la BD: ${total}`);
}

seed();
